language: java

install: true

before_deploy:
- echo - - - - - - - - - - - - - - - - - - -
- echo   M a v e n   P a c k a g i n g
- echo - - - - - - - - - - - - - - - - - - -
- mvn package
- echo - - - - - - - - - - - - - - - - -
- echo   E n d   M a v e n   P k g
- echo - - - - - - - - - - - - - - - - -
- ls -R
- chmod a+x ./deploy.sh
- ./deploy.sh

deploy:
  - provider: releases
    skip_cleanup: true
    api_key: $GITPERM
    file: target/*.jar
    on:
        tags: false
        branch: unstable
  - provider: releases
    skip_cleanup: true
    api_key: $GITPERM
    file: target/*.jar
    on:
        tags: false
        branch: develop

env:
- state=develop projectversion=0.0.2-SNAPSHOT