language: java

install: true

before_deploy:
- chmod +x ./deploy.sh
- ./deploy.sh

deploy:
  skip_cleanup: true
  - provider: releases
    api_key: $GITPERM
    file: 
        - target/ev3dev-lang-java-$projectversion-unstable-Build-$TRAVIS_BUILD_NUMBER.jar
        - target/ev3dev-lang-java-$projectversion-jar-with-dependencies-unstable-Build-$TRAVIS_BUILD_NUMBER.jar
    on:
        tags: false
        branch: unstable
  - provider: releases
    api_key: $GITPERM
    file: 
        - target/ev3dev-lang-java-$projectversion-develop-Build-$TRAVIS_BUILD_NUMBER.jar
        - target/ev3dev-lang-java-$projectversion-jar-with-dependencies-develop-Build-$TRAVIS_BUILD_NUMBER.jar
    on:
        tags: false
        branch: develop

env:
- state=develop
- projectversion=0.0.2-SNAPSHOT