language: java

install: true

before_deploy:
- ls -l
- chmod a+x ./deploy.sh
- ./deploy.sh

deploy:
  - provider: releases
    skip_cleanup: true
    api_key: $GITPERM
    file: target/*.jar
    on:
        tags: false
        branch: unstable
  - provider: releases
    skip_cleanup: true
    api_key: $GITPERM
    file: target/*.jar
    on:
        tags: false
        branch: develop

env:
- state=develop projectversion=0.0.2-SNAPSHOT